import {jobAge} from './age.mjs';
const $=id=>document.getElementById(id),escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const short=n=>'$'+(n/1000).toLocaleString('en-US',{maximumFractionDigits:1})+'k';
const pay=j=>short(j.salary.min)+(j.salary.max>j.salary.min?' – '+short(j.salary.max):'');
const modeClass=m=>m==='Hybrid'?'hybrid':m==='Remote'?'remote':m==='Not specified'?'unknown':'onsite';
const allLocations=j=>j.locations?.length?j.locations:[j.geo];
const date=d=>d?new Date(d).toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'}):'Not provided';
const stamp=d=>new Date(d).toLocaleString(undefined,{month:'short',day:'numeric',hour:'numeric',minute:'2-digit'});
let dataset=null,filtered=[],selectedId=null,map=null,layer=null,markers=new Map(),busy=false,lastLoaded=0,networkError=false;
try{if(!window.L)throw Error('Map library did not load');map=L.map('map',{zoomControl:false,minZoom:3,maxZoom:13,scrollWheelZoom:true}).setView([38.4,-97.5],4);L.control.zoom({position:'bottomleft'}).addTo(map);L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a>',maxZoom:19}).addTo(map);layer=L.layerGroup().addTo(map);fitUS();}catch(e){$('map').innerHTML='<div class="map-error">The map couldn’t load. You can still explore all openings in the list.</div>';}
function fitUS(){if(!map)return;const points=[[24.6,-125],[49.7,-66]];if(dataset)dataset.jobs.flatMap(allLocations).filter(g=>['AK','HI'].includes(g.state)&&Number.isFinite(g.lat)).forEach(g=>points.push([g.lat,g.lng]));map.fitBounds(points,{padding:[18,40],animate:false});}
function validData(d){return d&&Array.isArray(d.jobs)&&Array.isArray(d.sources)&&Number.isFinite(Date.parse(d.generatedAt))&&d.jobs.every(j=>j.id&&j.title&&j.company&&j.geo&&j.salary?.min>=100000&&/^https:\/\//.test(j.applyUrl));}
async function load(){if(busy)return;busy=true;$('refresh').disabled=true;try{const response=await fetch(`data/jobs.json?t=${Date.now()}`,{cache:'no-store',signal:AbortSignal.timeout(20000)});if(!response.ok)throw Error('Feed unavailable');const next=await response.json();if(!validData(next))throw Error('Feed format invalid');dataset=next;lastLoaded=Date.now();networkError=false;render();updateStatus();}catch(e){networkError=true;$('refresh-status').textContent=dataset?'Refresh failed · showing saved results':'Feed temporarily unavailable';$('live-dot').classList.add('stale');$('freshness').textContent='Could not check for updates. Use ↻ to retry.';if(!dataset)$('job-list').innerHTML='<div class="empty">The job feed couldn’t load. Check your connection, then press the refresh button above to try again.</div>';}finally{busy=false;$('refresh').disabled=false;}}
function updateStatus(){if(!dataset||networkError)return;const minutes=Math.max(0,Math.floor((Date.now()-Date.parse(dataset.generatedAt))/60000));const failed=dataset.sources.filter(s=>!s.ok).length;const stale=minutes>75||failed>0;const age=minutes<1?'just now':minutes<60?`${minutes}m ago`:`${Math.floor(minutes/60)}h ${minutes%60}m ago`;$('refresh-status').textContent=minutes>75?`Feed delayed · ${age}`:`Checked ${age} · every 30m`;$('live-dot').classList.toggle('stale',stale);$('freshness').textContent=`Last feed check ${stamp(dataset.generatedAt)} · ${dataset.sources.length-failed}/${dataset.sources.length} employer feeds available${failed?` · ${failed} feed${failed>1?'s':''} unavailable; saved listings labeled`:''}`;$('freshness').classList.toggle('stale-message',stale);}
function render(){
 const q=$('search').value.trim().toLowerCase(),mode=$('mode').value,sort=$('sort').value;
 // Hide expired fallback entries even if no subsequent refresh succeeds.
 const active=dataset.jobs.filter(j=>!j.stale||Date.now()-Date.parse(j.checkedAt)<86400000);
 filtered=active.filter(j=>(mode==='all'||j.workMode===mode)&&`${j.title} ${j.company} ${j.location}`.toLowerCase().includes(q));
 filtered.sort(sort==='salary'?(a,b)=>b.salary.min-a.salary.min:sort==='company'?(a,b)=>a.company.localeCompare(b.company):(a,b)=>(b.postedAt||'').localeCompare(a.postedAt||''));
 $('total-stat').textContent=active.length.toLocaleString();$('companies-stat').textContent=new Set(active.map(j=>j.company)).size;$('states-stat').textContent=new Set(active.flatMap(j=>allLocations(j).map(l=>l.state)).filter(Boolean)).size;
 $('result-count').textContent=`${filtered.length} position${filtered.length===1?'':'s'}${q||mode!=='all'?' found':''}`;$('clear').hidden=!q&&mode==='all';
 $('job-list').innerHTML=filtered.length?filtered.map(j=>{const a=jobAge(j.postedAt);return `<button class="job-card${selectedId===j.id?' selected':''}" data-id="${escape(j.id)}" style="--age-color:${a.color}" aria-label="${escape(j.title+' at '+j.company+', '+pay(j)+', '+j.workMode+', '+a.label)}"><div class="card-top"><span class="company">${escape(j.company)}</span><span class="badge ${modeClass(j.workMode)}">${escape(j.workMode)}</span></div><h2>${escape(j.title)}</h2><div class="location">${escape(j.location)}</div><div class="card-bottom"><span class="salary">${pay(j)} <span>/ yr</span></span><span class="age"><i style="background:${a.color}"></i>${escape(a.label)}</span></div>${j.stale?'<div class="stale-message age">Employer feed unavailable · saved listing</div>':''}</button>`;}).join(''):'<div class="empty">No positions match these filters. Try a different company, location, or work setting.</div>';
 $('job-list').querySelectorAll('[data-id]').forEach(el=>el.addEventListener('click',()=>selectJob(el.dataset.id)));
 if(selectedId&&!filtered.some(j=>j.id===selectedId)){selectedId=null;$('detail').hidden=true;}
 drawPins();
 $('source-status').innerHTML=dataset.sources.map(s=>`<div>${escape(s.company)} · ${s.ok?`${s.matches} jobs`:'feed unavailable'}</div>`).join('');
}
function drawPins(){if(!map)return;layer.clearLayers();markers.clear();const groups=new Map();for(const j of filtered){for(const geo of allLocations(j)){if(!Number.isFinite(geo.lat)||!Number.isFinite(geo.lng))continue;const key=`${geo.lat},${geo.lng}`;if(!groups.has(key))groups.set(key,[]);if(!groups.get(key).some(x=>x.id===j.id))groups.get(key).push({...j,geo});}}
 for(const jobs of groups.values()){
 const newest=[...jobs].sort((a,b)=>(b.postedAt||'').localeCompare(a.postedAt||''))[0],age=jobAge(newest.postedAt),size=jobs.length>1?32:16;
 const marker=L.marker([newest.geo.lat,newest.geo.lng],{icon:L.divIcon({className:'pin',html:`<span style="background:${age.color};width:100%;height:100%;border-radius:50%;display:grid;place-items:center">${jobs.length>1?jobs.length:''}</span>`,iconSize:[size,size],iconAnchor:[size/2,size/2]}),title:`${newest.geo.city||newest.location}: ${jobs.length} position${jobs.length===1?'':'s'}; newest ${age.label}`,keyboard:true}).addTo(layer);
 const tip=document.createElement('span');tip.textContent=`${newest.geo.city||newest.location} · ${jobs.length} position${jobs.length===1?'':'s'}`;marker.bindTooltip(tip,{direction:'top'});marker.on('click',()=>jobs.length===1?selectJob(jobs[0].id,false):showGroup(jobs));jobs.forEach(j=>markers.set(j.id,marker));
 }
 const unmapped=filtered.filter(j=>!allLocations(j).some(l=>Number.isFinite(l.lat))).length;$('map-note').textContent=`City-level pins · clusters use the newest job’s color${unmapped?` · ${unmapped} without a precise city (in list)`:''}`;
}
function showGroup(jobs){$('detail').hidden=false;const city=jobs[0].geo.city||jobs[0].location;$('detail').innerHTML=`<button class="close-detail" aria-label="Close city details">×</button><div class="eyebrow">${jobs.length} OPEN POSITIONS</div><h2>${escape(city)}, ${escape(jobs[0].geo.state||'')}</h2><div class="group-list">${[...jobs].sort((a,b)=>(b.postedAt||'').localeCompare(a.postedAt||'')).map(j=>`<button data-id="${escape(j.id)}"><i class="age-dot" style="background:${jobAge(j.postedAt).color}"></i>${escape(j.title)}<small>${escape(j.company)} · ${pay(j)} · ${escape(j.workMode)} · ${escape(jobAge(j.postedAt).label)}</small></button>`).join('')}</div>`;$('detail').querySelector('.close-detail').onclick=closeDetail;$('detail').querySelectorAll('[data-id]').forEach(b=>b.onclick=()=>selectJob(b.dataset.id,false));$('detail').querySelector('.close-detail').focus({preventScroll:true});}
function selectJob(id,pan=true){const j=filtered.find(j=>j.id===id);if(!j)return;selectedId=id;document.querySelectorAll('.job-card').forEach(c=>c.classList.toggle('selected',c.dataset.id===id));const age=jobAge(j.postedAt);$('detail').hidden=false;$('detail').innerHTML=`<button class="close-detail" aria-label="Close job details">×</button><div class="company">${escape(j.company)}</div><h2>${escape(j.title)}</h2><div class="location">${escape(j.location)}</div><span class="badge ${modeClass(j.workMode)}">${escape(j.workMode)}</span><div class="age"><i style="background:${age.color}"></i>${escape(age.label)}</div><div class="salary">${pay(j)} <span>/ year</span></div><ul class="facts">${j.facts.map(f=>`<li>${escape(f)}</li>`).join('')}${j.employmentType?`<li>${escape(j.employmentType.replace(/([a-z])([A-Z])/g,'$1 $2'))}</li>`:''}</ul>${j.workMode==='Not specified'?'<p class="detail-dates">The employer has not clearly specified a work setting. Confirm it before applying.</p>':''}<div class="detail-dates">${escape(j.postedLabel)}: ${date(j.postedAt)}<br>Last checked: ${stamp(j.checkedAt)}${j.stale?'<br><strong class="stale-message">Source unavailable; opening not re-verified.</strong>':''}</div><a class="apply" href="${escape(j.applyUrl)}" target="_blank" rel="noopener noreferrer">Apply on employer site ↗</a><a class="source-link" href="${escape(j.url)}" target="_blank" rel="noopener noreferrer">Read the full job description</a>`;$('detail').querySelector('.close-detail').onclick=closeDetail;$('detail').querySelector('.close-detail').focus({preventScroll:true});if(map&&pan&&Number.isFinite(j.geo.lat)){map.setView([j.geo.lat,j.geo.lng],Math.max(map.getZoom(),5),{animate:!matchMedia('(prefers-reduced-motion: reduce)').matches});}if(innerWidth<761)$('detail').scrollIntoView({block:'nearest',behavior:'instant'});}
function closeDetail(){const id=selectedId;selectedId=null;$('detail').hidden=true;document.querySelectorAll('.job-card').forEach(c=>{c.classList.remove('selected');if(c.dataset.id===id)c.focus({preventScroll:true});});}
$('search').addEventListener('input',()=>dataset&&render());$('mode').addEventListener('change',()=>dataset&&render());$('sort').addEventListener('change',()=>dataset&&render());$('clear').onclick=()=>{$('search').value='';$('mode').value='all';render();};$('reset-map').onclick=()=>{closeDetail();fitUS();};$('refresh').onclick=load;document.addEventListener('keydown',e=>{if(e.key==='Escape')closeDetail();});document.addEventListener('visibilitychange',()=>{if(!document.hidden&&Date.now()-lastLoaded>1800000)load();});setInterval(load,1800000);setInterval(updateStatus,60000);load();
