// Usage: node scripts/build-states.mjs path/to/states-10m.json [output.mjs]
// Source: https://cdn.jsdelivr.net/npm/us-atlas@3/states-10m.json
// Regenerates a dependency-free geographic basemap. License: vendor/US-ATLAS-LICENSE.
import {readFile, writeFile} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';

const [input, output = fileURLToPath(new URL('../us-states.mjs', import.meta.url)), ...extra] = process.argv.slice(2);
if (!input || extra.length) {
  console.error('Usage: node scripts/build-states.mjs path/to/states-10m.json [output.mjs]');
  process.exit(1);
}

const topology = JSON.parse(await readFile(input, 'utf8'));
if (topology.type !== 'Topology' || !Array.isArray(topology.arcs) || !Array.isArray(topology.objects?.states?.geometries)) {
  throw new Error('Expected unprojected us-atlas states-10m TopoJSON.');
}
const stateIds = new Set('01 02 04 05 06 08 09 10 11 12 13 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 44 45 46 47 48 49 50 51 53 54 55 56'.split(' '));
const decoded = new Map();
const samePoint = (a, b) => a[0] === b[0] && a[1] === b[1];

function decodeArc(reference) {
  if (!Number.isInteger(reference)) throw new Error('Arc reference must be an integer.');
  const index = reference < 0 ? ~reference : reference;
  if (!decoded.has(index)) {
    const arc = topology.arcs[index];
    if (!Array.isArray(arc) || arc.length < 2) throw new Error(`Invalid arc ${index}.`);
    let x = 0, y = 0;
    decoded.set(index, arc.map(point => {
      if (!Array.isArray(point) || !Number.isFinite(point[0]) || !Number.isFinite(point[1])) {
        throw new Error(`Invalid coordinate in arc ${index}.`);
      }
      // Quantized TopoJSON uses deltas, reset to zero for each arc.
      if (topology.transform) {
        x += point[0]; y += point[1];
        return [x * topology.transform.scale[0] + topology.transform.translate[0], y * topology.transform.scale[1] + topology.transform.translate[1]];
      }
      return point.slice(0, 2);
    }));
  }
  const coordinates = decoded.get(index);
  return reference < 0 ? [...coordinates].reverse() : coordinates;
}

let rings = 0, vertices = 0, west = Infinity, east = -Infinity;
function convertRing(references, stateId) {
  const stitched = [];
  for (const reference of references) {
    const arc = decodeArc(reference);
    if (stitched.length && !samePoint(stitched.at(-1), arc[0])) {
      throw new Error(`Disconnected arc in state ${stateId}.`);
    }
    stitched.push(...(stitched.length ? arc.slice(1) : arc));
  }
  if (!stitched.length || !samePoint(stitched[0], stitched.at(-1))) {
    throw new Error(`Unclosed ring in state ${stateId}.`);
  }
  const ring = stitched.map(([longitude, latitude]) => {
    if (longitude < -180 || longitude > 180 || latitude < -90 || latitude > 90) {
      throw new Error('Coordinates must be geographic longitude/latitude, not projected coordinates.');
    }
    // Put the Aleutians in the same map copy as the rest of Alaska.
    if (stateId === '02' && longitude > 0) longitude -= 360;
    return [Number(longitude.toFixed(4)), Number(latitude.toFixed(4))];
  });
  // As in topojson-client, pad tiny quantized rings to GeoJSON's four positions.
  while (ring.length < 4) ring.push([...ring[0]]);
  if (ring.length < 4 || !samePoint(ring[0], ring.at(-1))) {
    throw new Error(`Rounding produced an invalid ring in state ${stateId}.`);
  }
  for (let i = 0; i < ring.length; i++) {
    const [longitude] = ring[i];
    if (longitude < -190 || longitude > -60 || (i && Math.abs(longitude - ring[i - 1][0]) >= 180)) {
      throw new Error(`Discontinuous or unexpected longitude in state ${stateId}.`);
    }
    west = Math.min(west, longitude); east = Math.max(east, longitude);
  }
  rings++; vertices += ring.length;
  return ring;
}

const features = topology.objects.states.geometries
  .filter(geometry => stateIds.has(String(geometry.id).padStart(2, '0')))
  .map(geometry => {
    const id = String(geometry.id).padStart(2, '0');
    const polygon = arcs => arcs.map(ring => convertRing(ring, id));
    if (!['Polygon', 'MultiPolygon'].includes(geometry.type)) throw new Error(`Unsupported geometry type for state ${id}.`);
    return {
      type: 'Feature', id, properties: {name: geometry.properties.name},
      geometry: {
        type: geometry.type,
        coordinates: geometry.type === 'Polygon' ? polygon(geometry.arcs) : geometry.arcs.map(polygon),
      },
    };
  }).sort((a, b) => a.id.localeCompare(b.id));
if (features.length !== 51 || new Set(features.map(feature => feature.id)).size !== 51) {
  throw new Error('Expected exactly the 50 states and District of Columbia.');
}
const header = '// Generated by scripts/build-states.mjs; do not edit by hand.\n// Source: https://cdn.jsdelivr.net/npm/us-atlas@3/states-10m.json\n// License: vendor/US-ATLAS-LICENSE. Alaska longitudes cross the date line westward.\n';
const moduleText = `${header}export default ${JSON.stringify({type: 'FeatureCollection', features})};\n`;
await writeFile(output, moduleText);
console.log(`Wrote ${features.length} features, ${rings} closed rings, ${vertices} vertices, ${Buffer.byteLength(moduleText)} bytes; longitude range ${west} to ${east}.`);
