import test from 'node:test';
import assert from 'node:assert/strict';
import {layoutMarkers} from '../marker-layout.mjs';
const minSeparation=points=>Math.min(...points.flatMap((a,i)=>points.slice(i+1).map(b=>Math.hypot(a.x-b.x,a.y-b.y))));
const bounds={left:24,right:626,top:48,bottom:430};

test('isolated cities remain at their true anchors',()=>{const points=[{id:'a',x:100,y:100},{id:'b',x:400,y:100},{id:'c',x:100,y:400}];assert.deepEqual(layoutMarkers(points,{bounds}),points.map(p=>({...p,dx:0,dy:0})));});
test('nearby circles separate locally without moving a distant city',()=>{const points=[{id:'a',x:200,y:200},{id:'b',x:205,y:205},{id:'far',x:600,y:300}];const result=layoutMarkers(points,{bounds});assert(minSeparation(result)>=49.9);assert.deepEqual(result[2],{...points[2],dx:0,dy:0});assert(result.slice(0,2).every(p=>Math.hypot(p.dx,p.dy)<30));});
test('twenty dense cities get distinct positions with bounded displacement',()=>{const points=Array.from({length:20},(_,i)=>({id:`city-${i}`,x:320+(i%5)*2,y:230+Math.floor(i/5)*2}));const result=layoutMarkers(points,{bounds,minDistance:52});assert(minSeparation(result)>=51.8,`minimum ${minSeparation(result)}`);assert(result.every(p=>Math.hypot(p.dx,p.dy)<=160.0001));});
test('coincident anchors resolve deterministically regardless of incoming sort order',()=>{const points=Array.from({length:12},(_,i)=>({id:`city-${i}`,x:300,y:240}));const first=layoutMarkers(points,{bounds}),second=layoutMarkers([...points].reverse(),{bounds}).reverse();assert.deepEqual(first,second);assert.deepEqual(first,layoutMarkers(points,{bounds}));assert(minSeparation(first)>=49.8);});
test('offscreen country anchors stay offscreen instead of collecting along viewport edges',()=>{const points=[{id:'a',x:200,y:200},{id:'b',x:201,y:201},{id:'distant-a',x:-2000,y:10},{id:'distant-b',x:-2001,y:11}];const result=layoutMarkers(points,{bounds});assert.deepEqual(result.slice(2),points.slice(2).map(p=>({...p,dx:0,dy:0})));});
test('an edge cluster spreads inside available viewport bounds',()=>{const points=Array.from({length:8},(_,i)=>({id:`edge-${i}`,x:30+i%2,y:80+Math.floor(i/2)}));const result=layoutMarkers(points,{bounds,maxDisplacement:160});assert(minSeparation(result)>=49.8,`minimum ${minSeparation(result)}`);assert(result.every(p=>p.x>=bounds.left-.1&&p.x<=bounds.right+.1&&p.y>=bounds.top-.1&&p.y<=bounds.bottom+.1));});
test('layout follows zoom scale and returns cities to true anchors when separation is sufficient',()=>{const close=[{id:'a',x:100,y:100},{id:'b',x:110,y:100}],far=[{id:'a',x:100,y:100},{id:'b',x:160,y:100}];assert(layoutMarkers(close).some(p=>p.dx!==0));assert(layoutMarkers(far).every(p=>p.dx===0&&p.dy===0));});
test('impossible packing still respects the maximum displacement',()=>{const points=Array.from({length:30},(_,i)=>({id:String(i),x:100,y:100}));const result=layoutMarkers(points,{maxDisplacement:40});assert(result.every(p=>Math.hypot(p.dx,p.dy)<=40.0001));});

test('mixed marker sizes reserve each circle and halo without wasting pie-sized gaps',()=>{const points=[{id:'pie',x:200,y:200,radius:26},{id:'single',x:201,y:200,radius:18},{id:'small-a',x:350,y:200,radius:18},{id:'small-b',x:351,y:200,radius:18}];const result=layoutMarkers(points,{bounds,minDistance:52});assert(Math.hypot(result[0].x-result[1].x,result[0].y-result[1].y)>=43.9);assert(Math.hypot(result[2].x-result[3].x,result[2].y-result[3].y)>=35.9);assert(Math.hypot(result[2].dx,result[2].dy)<20);});
